<?php

/**
 * Closed system permission catalog.
 * Households may compose roles from these keys only.
 */
return [
    'admin_capability' => 'roles.gestionar',

    'catalog' => [
        ['key' => 'hogar.ver', 'name' => 'Ver hogar', 'description' => 'Consultar datos del hogar', 'group' => 'hogar'],
        ['key' => 'hogar.editar', 'name' => 'Editar hogar', 'description' => 'Modificar configuración del hogar', 'group' => 'hogar'],
        ['key' => 'hogar.eliminar', 'name' => 'Eliminar hogar', 'description' => 'Eliminar el hogar', 'group' => 'hogar'],
        ['key' => 'miembros.ver', 'name' => 'Ver integrantes', 'description' => 'Listar integrantes del hogar', 'group' => 'miembros'],
        ['key' => 'miembros.gestionar', 'name' => 'Gestionar integrantes', 'description' => 'Suspender o actualizar integrantes', 'group' => 'miembros'],
        ['key' => 'miembros.crear', 'name' => 'Crear integrantes', 'description' => 'Crear cuentas y vincularlas al hogar', 'group' => 'miembros'],
        ['key' => 'roles.ver', 'name' => 'Ver roles', 'description' => 'Consultar roles y permisos', 'group' => 'roles'],
        ['key' => 'roles.gestionar', 'name' => 'Gestionar roles', 'description' => 'Crear y modificar roles y permisos', 'group' => 'roles'],
        ['key' => 'cuentas.ver', 'name' => 'Ver cuentas financieras', 'description' => 'Consultar cuentas del hogar autorizadas', 'group' => 'cuentas'],
        ['key' => 'cuentas.gestionar', 'name' => 'Gestionar cuentas financieras', 'description' => 'Crear y desactivar cuentas del hogar', 'group' => 'cuentas'],
        ['key' => 'categorias.ver', 'name' => 'Ver categorías', 'description' => 'Consultar categorías financieras', 'group' => 'categorias'],
        ['key' => 'categorias.gestionar', 'name' => 'Gestionar categorías', 'description' => 'Crear y desactivar categorías financieras', 'group' => 'categorias'],
        ['key' => 'ingresos.ver_propios', 'name' => 'Ver ingresos propios', 'description' => null, 'group' => 'ingresos'],
        ['key' => 'ingresos.ver_compartidos', 'name' => 'Ver ingresos compartidos', 'description' => null, 'group' => 'ingresos'],
        ['key' => 'ingresos.ver_ajenos', 'name' => 'Ver ingresos ajenos', 'description' => null, 'group' => 'ingresos'],
        ['key' => 'ingresos.crear', 'name' => 'Crear ingresos', 'description' => null, 'group' => 'ingresos'],
        ['key' => 'ingresos.editar_propios', 'name' => 'Editar ingresos propios', 'description' => null, 'group' => 'ingresos'],
        ['key' => 'ingresos.editar_ajenos', 'name' => 'Editar ingresos ajenos', 'description' => null, 'group' => 'ingresos'],
        ['key' => 'ingresos.eliminar', 'name' => 'Eliminar ingresos', 'description' => null, 'group' => 'ingresos'],
        ['key' => 'gastos.ver_propios', 'name' => 'Ver gastos propios', 'description' => null, 'group' => 'gastos'],
        ['key' => 'gastos.ver_compartidos', 'name' => 'Ver gastos compartidos', 'description' => null, 'group' => 'gastos'],
        ['key' => 'gastos.ver_ajenos', 'name' => 'Ver gastos ajenos', 'description' => null, 'group' => 'gastos'],
        ['key' => 'gastos.crear', 'name' => 'Crear gastos', 'description' => null, 'group' => 'gastos'],
        ['key' => 'gastos.editar', 'name' => 'Editar gastos', 'description' => null, 'group' => 'gastos'],
        ['key' => 'gastos.eliminar', 'name' => 'Eliminar gastos', 'description' => null, 'group' => 'gastos'],
        ['key' => 'gastos.registrar_pago', 'name' => 'Registrar pagos', 'description' => null, 'group' => 'gastos'],
        ['key' => 'pagos.ver', 'name' => 'Ver pagos', 'description' => 'Consultar pagos de gastos autorizados', 'group' => 'pagos'],
        ['key' => 'recurrencias.ver', 'name' => 'Ver recurrencias', 'description' => 'Consultar plantillas recurrentes', 'group' => 'recurrencias'],
        ['key' => 'recurrencias.gestionar', 'name' => 'Gestionar recurrencias', 'description' => 'Crear y generar ocurrencias recurrentes', 'group' => 'recurrencias'],
        ['key' => 'deudas.ver_propias', 'name' => 'Ver deudas propias', 'description' => null, 'group' => 'deudas'],
        ['key' => 'deudas.ver_compartidas', 'name' => 'Ver deudas compartidas', 'description' => null, 'group' => 'deudas'],
        ['key' => 'deudas.ver_ajenas', 'name' => 'Ver deudas ajenas', 'description' => null, 'group' => 'deudas'],
        ['key' => 'deudas.ver_totales', 'name' => 'Ver totales de deudas', 'description' => null, 'group' => 'deudas'],
        ['key' => 'deudas.crear', 'name' => 'Crear deudas', 'description' => null, 'group' => 'deudas'],
        ['key' => 'deudas.editar', 'name' => 'Editar deudas', 'description' => null, 'group' => 'deudas'],
        ['key' => 'deudas.planificar', 'name' => 'Planificar deudas', 'description' => null, 'group' => 'deudas'],
        ['key' => 'reglas.ver', 'name' => 'Ver reglas', 'description' => null, 'group' => 'reglas'],
        ['key' => 'reglas.simular', 'name' => 'Simular reglas', 'description' => null, 'group' => 'reglas'],
        ['key' => 'reglas.aplicar', 'name' => 'Aplicar reglas', 'description' => null, 'group' => 'reglas'],
        ['key' => 'ahorros.ver_propios', 'name' => 'Ver ahorros propios', 'description' => null, 'group' => 'ahorros'],
        ['key' => 'ahorros.ver_compartidos', 'name' => 'Ver ahorros compartidos', 'description' => null, 'group' => 'ahorros'],
        ['key' => 'ahorros.ver_ajenos', 'name' => 'Ver ahorros ajenos', 'description' => null, 'group' => 'ahorros'],
        ['key' => 'ahorros.gestionar', 'name' => 'Gestionar ahorros', 'description' => null, 'group' => 'ahorros'],
        ['key' => 'presupuestos.ver', 'name' => 'Ver presupuestos', 'description' => null, 'group' => 'presupuestos'],
        ['key' => 'presupuestos.gestionar', 'name' => 'Gestionar presupuestos', 'description' => null, 'group' => 'presupuestos'],
        ['key' => 'mercado.ver', 'name' => 'Ver lista de mercado', 'description' => null, 'group' => 'mercado'],
        ['key' => 'mercado.gestionar', 'name' => 'Gestionar lista de mercado', 'description' => null, 'group' => 'mercado'],
        ['key' => 'cierres.ejecutar', 'name' => 'Ejecutar cierres', 'description' => null, 'group' => 'cierres'],
        ['key' => 'cierres.reabrir', 'name' => 'Reabrir cierres', 'description' => null, 'group' => 'cierres'],
        ['key' => 'auditoria.ver', 'name' => 'Ver auditoría', 'description' => null, 'group' => 'auditoria'],
        ['key' => 'datos.exportar', 'name' => 'Exportar datos', 'description' => null, 'group' => 'datos'],
    ],
];
